import type { Transaction } from "./types";

export const initialTransactions: Transaction[] = [
  {
    id: 1,
    date: "2025-10-15",
    description: "Grocery Shopping",
    category: "Food",
    amount: -150,
    method: "Cash",
    type: "Expenses",
  },
  {
    id: 2,
    date: "2025-10-14",
    description: "Salary",
    category: "Income",
    amount: 3000,
    method: "Account",
    type: "Income",
  },
  {
    id: 3,
    date: "2025-10-13",
    description: "Gas",
    category: "Transport",
    amount: -80,
    method: "Card",
    type: "Expenses",
  },
  {
    id: 4,
    date: "2025-10-12",
    description: "Freelance Work",
    category: "Income",
    amount: 1500,
    method: "Account",
    type: "Income",
  },
  {
    id: 5,
    date: "2025-10-11",
    description: "Rent",
    category: "Housing",
    amount: -1200,
    method: "Account",
    type: "Expenses",
  },
  {
    id: 6,
    date: "2025-10-15",
    description: "Bank Transfer",
    amount: 1000,
    method: "Account",
    type: "Transfer",
    hasFees: true,
    feesAmount: 10,
    transferTarget: "Other",
  },
  {
    id: 7,
    date: "2023-12-15",
    description: "Bank Transfer",
    amount: 1000,
    method: "Account",
    type: "Transfer",
    hasFees: true,
    feesAmount: 10,
    transferTarget: "Other",
  },
];
