export const currencyMap: Record<
string,
  { code: string; symbol: string; name: string }
> = {
  AF: { code: "AFN", symbol: "؋", name: "Afghan Afghani" },
  AL: { code: "ALL", symbol: "L", name: "Albanian Lek" },
  DZ: { code: "DZD", symbol: "د.ج", name: "Algerian Dinar" },
  AS: { code: "USD", symbol: "$", name: "US Dollar" },
  AD: { code: "EUR", symbol: "€", name: "Euro" },
  AO: { code: "AOA", symbol: "Kz", name: "Angolan Kwanza" },
  AR: { code: "ARS", symbol: "$", name: "Argentine Peso" },
  AM: { code: "AMD", symbol: "֏", name: "Armenian Dram" },
  AU: { code: "AUD", symbol: "$", name: "Australian Dollar" },
  AT: { code: "EUR", symbol: "€", name: "Euro" },
  AZ: { code: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
  BS: { code: "BSD", symbol: "$", name: "Bahamian Dollar" },
  BH: { code: "BHD", symbol: ".د.ب", name: "Bahraini Dinar" },
  BD: { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  BB: { code: "BBD", symbol: "$", name: "Barbadian Dollar" },
  BY: { code: "BYN", symbol: "Br", name: "Belarusian Ruble" },
  BE: { code: "EUR", symbol: "€", name: "Euro" },
  BZ: { code: "BZD", symbol: "$", name: "Belize Dollar" },
  BJ: { code: "XOF", symbol: "CFA", name: "West African CFA Franc" },
  BT: { code: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum" },
  BO: { code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano" },
  BA: { code: "BAM", symbol: "KM", name: "Bosnia and Herzegovina Convertible Mark" },
  BW: { code: "BWP", symbol: "P", name: "Botswana Pula" },
  BR: { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  BN: { code: "BND", symbol: "$", name: "Brunei Dollar" },
  BG: { code: "BGN", symbol: "лв", name: "Bulgarian Lev" },
  BF: { code: "XOF", symbol: "CFA", name: "West African CFA Franc" },
  BI: { code: "BIF", symbol: "FBu", name: "Burundian Franc" },
  KH: { code: "KHR", symbol: "៛", name: "Cambodian Riel" },
  CM: { code: "XAF", symbol: "CFA", name: "Central African CFA Franc" },
  CA: { code: "CAD", symbol: "$", name: "Canadian Dollar" },
  CV: { code: "CVE", symbol: "$", name: "Cape Verdean Escudo" },
  CF: { code: "XAF", symbol: "CFA", name: "Central African CFA Franc" },
  TD: { code: "XAF", symbol: "CFA", name: "Central African CFA Franc" },
  CL: { code: "CLP", symbol: "$", name: "Chilean Peso" },
  CN: { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  CO: { code: "COP", symbol: "$", name: "Colombian Peso" },
  KM: { code: "KMF", symbol: "CF", name: "Comorian Franc" },
  CG: { code: "XAF", symbol: "CFA", name: "Central African CFA Franc" },
  CR: { code: "CRC", symbol: "₡", name: "Costa Rican Colón" },
  HR: { code: "EUR", symbol: "€", name: "Euro" },
  CU: { code: "CUP", symbol: "₱", name: "Cuban Peso" },
  CY: { code: "EUR", symbol: "€", name: "Euro" },
  CZ: { code: "CZK", symbol: "Kč", name: "Czech Koruna" },
  DK: { code: "DKK", symbol: "kr", name: "Danish Krone" },
  DJ: { code: "DJF", symbol: "Fdj", name: "Djiboutian Franc" },
  DO: { code: "DOP", symbol: "RD$", name: "Dominican Peso" },
  EC: { code: "USD", symbol: "$", name: "US Dollar" },
  EG: { code: "EGP", symbol: "£", name: "Egyptian Pound" },
  SV: { code: "USD", symbol: "$", name: "US Dollar" },
  EE: { code: "EUR", symbol: "€", name: "Euro" },
  ET: { code: "ETB", symbol: "Br", name: "Ethiopian Birr" },
  FI: { code: "EUR", symbol: "€", name: "Euro" },
  FR: { code: "EUR", symbol: "€", name: "Euro" },
  GA: { code: "XAF", symbol: "CFA", name: "Central African CFA Franc" },
  GM: { code: "GMD", symbol: "D", name: "Gambian Dalasi" },
  GE: { code: "GEL", symbol: "₾", name: "Georgian Lari" },
  DE: { code: "EUR", symbol: "€", name: "Euro" },
  GH: { code: "GHS", symbol: "₵", name: "Ghanaian Cedi" },
  GR: { code: "EUR", symbol: "€", name: "Euro" },
  GT: { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal" },
  GN: { code: "GNF", symbol: "FG", name: "Guinean Franc" },
  GY: { code: "GYD", symbol: "$", name: "Guyanese Dollar" },
  HT: { code: "HTG", symbol: "G", name: "Haitian Gourde" },
  HN: { code: "HNL", symbol: "L", name: "Honduran Lempira" },
  HK: { code: "HKD", symbol: "$", name: "Hong Kong Dollar" },
  HU: { code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  IS: { code: "ISK", symbol: "kr", name: "Icelandic Krona" },
  IN: { code: "INR", symbol: "₹", name: "Indian Rupee" },
  ID: { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  IR: { code: "IRR", symbol: "﷼", name: "Iranian Rial" },
  IQ: { code: "IQD", symbol: "ع.د", name: "Iraqi Dinar" },
  IE: { code: "EUR", symbol: "€", name: "Euro" },
  IL: { code: "ILS", symbol: "₪", name: "Israeli Shekel" },
  IT: { code: "EUR", symbol: "€", name: "Euro" },
  JM: { code: "JMD", symbol: "J$", name: "Jamaican Dollar" },
  JP: { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  JO: { code: "JOD", symbol: "د.ا", name: "Jordanian Dinar" },
  KZ: { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
  KE: { code: "KES", symbol: "Sh", name: "Kenyan Shilling" },
  KR: { code: "KRW", symbol: "₩", name: "South Korean Won" },
  KW: { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
  LA: { code: "LAK", symbol: "₭", name: "Lao Kip" },
  LV: { code: "EUR", symbol: "€", name: "Euro" },
  LB: { code: "LBP", symbol: "ل.ل", name: "Lebanese Pound" },
  LR: { code: "LRD", symbol: "$", name: "Liberian Dollar" },
  LY: { code: "LYD", symbol: "ل.د", name: "Libyan Dinar" },
  LT: { code: "EUR", symbol: "€", name: "Euro" },
  LU: { code: "EUR", symbol: "€", name: "Euro" },
  MO: { code: "MOP", symbol: "MOP$", name: "Macanese Pataca" },
  MG: { code: "MGA", symbol: "Ar", name: "Malagasy Ariary" },
  MW: { code: "MWK", symbol: "MK", name: "Malawian Kwacha" },
  MY: { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  MV: { code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa" },
  ML: { code: "XOF", symbol: "CFA", name: "West African CFA Franc" },
  MT: { code: "EUR", symbol: "€", name: "Euro" },
  MX: { code: "MXN", symbol: "$", name: "Mexican Peso" },
  MD: { code: "MDL", symbol: "L", name: "Moldovan Leu" },
  MN: { code: "MNT", symbol: "₮", name: "Mongolian Tögrög" },
  MA: { code: "MAD", symbol: "د.م.", name: "Moroccan Dirham" },
  MZ: { code: "MZN", symbol: "MT", name: "Mozambican Metical" },
  MM: { code: "MMK", symbol: "Ks", name: "Myanmar Kyat" },
  NA: { code: "NAD", symbol: "$", name: "Namibian Dollar" },
  NP: { code: "NPR", symbol: "₨", name: "Nepalese Rupee" },
  NL: { code: "EUR", symbol: "€", name: "Euro" },
  NZ: { code: "NZD", symbol: "$", name: "New Zealand Dollar" },
  NG: { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  NO: { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  OM: { code: "OMR", symbol: "﷼", name: "Omani Rial" },
  PK: { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
  PA: { code: "PAB", symbol: "B/.", name: "Panamanian Balboa" },
  PY: { code: "PYG", symbol: "₲", name: "Paraguayan Guaraní" },
  PE: { code: "PEN", symbol: "S/", name: "Peruvian Sol" },
  PH: { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  PL: { code: "PLN", symbol: "zł", name: "Polish Zloty" },
  PT: { code: "EUR", symbol: "€", name: "Euro" },
  QA: { code: "QAR", symbol: "﷼", name: "Qatari Riyal" },
  RO: { code: "RON", symbol: "lei", name: "Romanian Leu" },
  RU: { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  RW: { code: "RWF", symbol: "FRw", name: "Rwandan Franc" },
  SA: { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
  RS: { code: "RSD", symbol: "дин.", name: "Serbian Dinar" },
  SG: { code: "SGD", symbol: "$", name: "Singapore Dollar" },
  SK: { code: "EUR", symbol: "€", name: "Euro" },
  SI: { code: "EUR", symbol: "€", name: "Euro" },
  ZA: { code: "ZAR", symbol: "R", name: "South African Rand" },
  ES: { code: "EUR", symbol: "€", name: "Euro" },
  LK: { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  SE: { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  CH: { code: "CHF", symbol: "Fr", name: "Swiss Franc" },
  TW: { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar" },
  TH: { code: "THB", symbol: "฿", name: "Thai Baht" },
  TR: { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  UA: { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
  AE: { code: "AED", symbol: "د.إ", name: "UAE Dirham" },
  GB: { code: "GBP", symbol: "£", name: "British Pound" },
  US: { code: "USD", symbol: "$", name: "US Dollar" },
  UY: { code: "UYU", symbol: "$U", name: "Uruguayan Peso" },
  UZ: { code: "UZS", symbol: "soʻm", name: "Uzbekistani Som" },
  VE: { code: "VES", symbol: "Bs", name: "Venezuelan Bolívar" },
  VN: { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
  YE: { code: "YER", symbol: "﷼", name: "Yemeni Rial" },
  ZM: { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
  ZW: { code: "ZWL", symbol: "$", name: "Zimbabwean Dollar" },
};

export function getCurrencyByCountryCode(countryCode: string) {
  return currencyMap[countryCode.toUpperCase()] || currencyMap["US"];
}